dist: trusty
before_install:
- openssl aes-256-cbc -K $encrypted_82da6839b977_key -iv $encrypted_82da6839b977_iv
  -in config/travisci_rsa.enc -out config/travisci_rsa -d
#- sudo apt-get update
- sudo apt-get install doxygen graphviz
- chmod 0600 config/travisci_rsa
- cp config/travisci_rsa ~/.ssh/id_rsa
- chmod 700 config/publish-doxygen
- "./config/publish-doxygen"

notifications:
 email:false